name: Code quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      - name: RuboCop Linter
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop
