name: Specs
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run specs
      env:
        RUBYOPT: -W:no-deprecated
      run: |
        bundle exec rake test
        bundle exec rspec --format documentation --require spec_helper
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
